language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

jobs:
  include:
    - stage: "Code Analysis"
      name: "TS Lint"            
      script:
      - ng lint

    - stage: "Test"
      name: "Unit Test"            
      script:
      - npm run test

    - stage: "Build"
      script: 
      - ng build --prod --base-href https://laszlokesik.github.io/ctl-fe/

    - stage: "Deploy"
      name: "Deploy to GitHub Pages"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/ctl-fe
        on:
          branch: master

